name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        java-version: '14'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
